// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTaggedWorld.Data;

#nullable disable

namespace WebApiTaggedWorld.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230128203751_SharingsChange")]
    partial class SharingsChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("TaggedWorldLibrary.Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.Member", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.Target", b =>
                {
                    b.Property<int>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AccessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SharedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SharedOnGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccessedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserModifiedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserOwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserSenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TargetId");

                    b.HasIndex("SharedOnGroupId");

                    b.HasIndex("UserAccessedId");

                    b.HasIndex("UserModifiedId");

                    b.HasIndex("UserOwnerId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasAlternateKey("Email");

                    b.HasAlternateKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.Member", b =>
                {
                    b.HasOne("TaggedWorldLibrary.Model.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaggedWorldLibrary.Model.User", "User")
                        .WithMany("MemberOf")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.Target", b =>
                {
                    b.HasOne("TaggedWorldLibrary.Model.Group", "SharedOnGroup")
                        .WithMany()
                        .HasForeignKey("SharedOnGroupId");

                    b.HasOne("TaggedWorldLibrary.Model.User", "UserAccessed")
                        .WithMany("AccessedTargets")
                        .HasForeignKey("UserAccessedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaggedWorldLibrary.Model.User", "UserModified")
                        .WithMany("ModifiedTargets")
                        .HasForeignKey("UserModifiedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaggedWorldLibrary.Model.User", "UserOwner")
                        .WithMany("OwnedTargets")
                        .HasForeignKey("UserOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaggedWorldLibrary.Model.User", "UserSender")
                        .WithMany()
                        .HasForeignKey("UserSenderId");

                    b.Navigation("SharedOnGroup");

                    b.Navigation("UserAccessed");

                    b.Navigation("UserModified");

                    b.Navigation("UserOwner");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TaggedWorldLibrary.Model.User", b =>
                {
                    b.Navigation("AccessedTargets");

                    b.Navigation("MemberOf");

                    b.Navigation("ModifiedTargets");

                    b.Navigation("OwnedTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
